---
- name: Preparing the inventory file
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Create the inventory file
      template:
        src: "{{ scripts }}/template/inventory.j2"
        dest: "{{ scripts }}/inventory"
        force: true
...
