---
- name: Preparing the inventory file
  hosts: localhost
  become: true
  become_method: sudo
  vars_files:
    - input.yaml
  tasks:
    - name: Create the inventory file
      template:
        src: "inventory.j2"
        dest: "inventory"
        force: true
...
